"""Thin wrapper around Gemini's image-to-image generation.

`google-genai` is this route's only new dependency, and this is the only
function that imports it (lazily, inside the function body) - the rest of
this module, and the rest of the repo, work with zero knowledge of Gemini or
`google-genai`, the same opt-in-dependency pattern
Image_Process/image_to_mondrian/face_protection.py uses for mediapipe.

NOT YET VERIFIED against a real API call (no GEMINI_API_KEY available while
writing this) - the exact call shape below (contents=[prompt, image part],
reading generated bytes back out of response.candidates[0].content.parts)
matches the google-genai SDK's documented image-generation pattern, but
needs confirming/fixing against an actual response once a key is available.
"""

import mimetypes
import os
from pathlib import Path


class GeminiConfigError(RuntimeError):
    """Raised for anything that stops us from even attempting the API call
    (missing key, unreadable source image) - distinct from an API-level
    failure, so callers can tell "you forgot to set env var X" apart from
    "Gemini's servers rejected the request"."""


def generate_styled_image(source_image_path: Path, prompt: str, model: str) -> bytes:
    """Sends `source_image_path` + `prompt` to Gemini's image-to-image
    generation and returns the generated image's raw bytes.

    Raises GeminiConfigError if GEMINI_API_KEY isn't set or the source image
    can't be read - never silently falls back to anything. Raises whatever
    the google-genai SDK itself raises for API-level failures (network,
    quota, invalid model, etc.) - not wrapped, so the real error reaches the
    caller.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise GeminiConfigError(
            "GEMINI_API_KEY environment variable is not set - this route needs "
            "a Gemini API key (see Image_Process/gemini_mondrian/README.md)."
        )

    source_image_path = Path(source_image_path)
    if not source_image_path.is_file():
        raise GeminiConfigError(f"source image not found: {source_image_path}")
    image_bytes = source_image_path.read_bytes()
    mime_type = mimetypes.guess_type(str(source_image_path))[0] or "image/jpeg"

    from google import genai  # lazy import - see module docstring
    from google.genai import types

    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model=model,
        contents=[
            prompt,
            types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
        ],
    )

    for part in response.candidates[0].content.parts:
        if getattr(part, "inline_data", None) is not None:
            return part.inline_data.data

    raise RuntimeError(
        "Gemini response didn't contain a generated image - "
        "check the prompt/model, or that this model supports image output."
    )
